name: image_stable_build
on:
  workflow_dispatch:
#  schedule:
#    - cron:  '30 2 * * 1'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        DEVICE: [q706f]
        EDITION: [gnome,kde-plasma,plasma-mobile,phosh,minimal]
        BRANCH: [stable]
    steps:
      -
        id: time
        uses: boredland/get-time-action@2.0.0
        with:
          timeZone: 8
          format: 'YYYYMMDD'
      -
        id: image-build
        uses: silime/lenovo-q706f-images@main
        with:
          arm-profiles-repo: https://github.com/silime/arm-profiles
          device: ${{ matrix.device }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          version: ${{ steps.time.outputs.time }}
          #gpg-key: ${{ secrets.CI_GPG_SECRET }}
          #gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
      -
        name: Release assets
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: true
          files: |
            ${{ env.FILE_PATH }}
            ${{ env.ROOTFS_PATH }}
            ${{ env.FILE_SHA256 }}
            ${{ env.FILE_TORRENT }}
            ${{ env.FILE_PKG }}
            #${{ env.FILE_SIG }}